name: Build Application

on:
  push:
    branches:
      - main
    paths:
      - "app/**"
      - ".github/workflows/**"
  pull_request:
    paths:
        - "app/**"
        - ".github/workflows/**"

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        
      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install -r requirements.txt

      - name: Build Executable
        run: |
          pyinstaller --onefile --windowed --name DownAndSync --icon=app/assets/icon.ico --add-data "app/styles/dark_theme.qss;styles" app/main.py
        shell: cmd

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: DownAndSync
          path: dist/DownAndSync.exe

      - name: Create GitHub Release and Upload Executable
        uses: softprops/action-gh-release@v1
        with:
          files: dist/DownAndSync.exe
          tag_name: "DownAndSync-windows-1.0.${{ github.run_number }}"
          body: "DownAndSync Release ${{ github.run_number }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
    
